services:
  telegram-bot:
    build: .
    container_name: tg-mso-bot
    restart: unless-stopped
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ADMINS=${ADMINS}
      - LOG_CHAT=${LOG_CHAT}
    volumes:
      - ./data/profiles.json:/app/data/profiles.json        # persist / override config
      - ./data/messages.json:/app/data/messages.json
      - ./data/results.json:/app/data/results.json
      - ./data/stats.json:/app/data/stats.json
