services:
  telegram-bot:
    build: .
    container_name: tg-mso-bot
    restart: unless-stopped
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ADMINS=${ADMINS}
    volumes:
      - ./profiles.json:/app/profiles.json        # persist / override config
      - ./messages.json:/app/messages.json
